# Generated by Django 3.2.8 on 2021-11-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211124_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialy',
            name='dupa',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
